spring:
  datasource:
    url: jdbc:h2:file:/data/auth-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    enabled: false
app:
  sincronizacion:
    url-nube: "http://192.168.0.14:9086"
    intervalo: 60000
    admin-user: "admin"
    admin-pass: "admin"
