server:
  port: 8761

spring:
  application:
    name: eureka-service
  datasource:
    url: jdbc:h2:file:/data/eureka-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    hostname: eureka-service-online
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

app:
  offline-mode: true
  sincronizacion:
    url-nube: "http://192.168.0.14:9083"
    intervalo: 60000
