spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:postgres-db}:${DB_PORT:5432}/${DB_NAME:ecopila_db_online}
    username: ${DB_USER:admin}
    password: ${DB_PASS:password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  cloud:
    config:
      fail-fast: true # Le dice a la app que falle si no puede conectar al arrancar
      retry:
        initial-interval: 2000 # Espera 2 segundos antes del primer reintento
        max-interval: 10000   # Tiempo máximo de espera entre reintentos (10s)
        multiplier: 1.5       # Multiplica el intervalo en cada reintento
        max-attempts: 10 
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service-online:8761/eureka/
